CREATE TABLE IF NOT EXISTS db_order (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Order id',
    order_no VARCHAR(64) NOT NULL COMMENT 'Order number',
    user_id BIGINT NOT NULL COMMENT 'User id, references db_user.uid',
    course_id BIGINT NOT NULL COMMENT 'Course id, references db_course.id',
    course_title VARCHAR(100) NOT NULL COMMENT 'Course title snapshot',
    course_subtitle VARCHAR(255) DEFAULT NULL COMMENT 'Course subtitle snapshot',
    course_cover_url VARCHAR(500) DEFAULT NULL COMMENT 'Course cover url snapshot',
    teacher_id BIGINT DEFAULT NULL COMMENT 'Teacher id snapshot',
    teacher_name VARCHAR(100) DEFAULT NULL COMMENT 'Teacher name snapshot',
    original_amount DECIMAL(10, 2) NOT NULL DEFAULT 0.00 COMMENT 'Original amount snapshot',
    pay_amount DECIMAL(10, 2) NOT NULL DEFAULT 0.00 COMMENT 'Pay amount',
    discount_amount DECIMAL(10, 2) NOT NULL DEFAULT 0.00 COMMENT 'Discount amount',
    order_status VARCHAR(32) NOT NULL COMMENT 'Order status',
    pay_status VARCHAR(32) NOT NULL COMMENT 'Pay status',
    pay_type VARCHAR(32) NOT NULL COMMENT 'Pay type',
    pay_time DATETIME DEFAULT NULL COMMENT 'Pay time',
    cancel_time DATETIME DEFAULT NULL COMMENT 'Cancel time',
    expire_time DATETIME DEFAULT NULL COMMENT 'Expire time',
    remark VARCHAR(255) DEFAULT NULL COMMENT 'Remark',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated time',
    UNIQUE KEY uk_order_no (order_no),
    KEY idx_user_id (user_id),
    KEY idx_course_id (course_id),
    KEY idx_order_status (order_status),
    KEY idx_pay_status (pay_status),
    KEY idx_created_at (created_at)
) COMMENT='Course enrollment order';

CREATE TABLE IF NOT EXISTS db_order_status_log (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Log id',
    order_id BIGINT NOT NULL COMMENT 'Order id',
    order_no VARCHAR(64) NOT NULL COMMENT 'Order number',
    old_order_status VARCHAR(32) DEFAULT NULL COMMENT 'Old order status',
    new_order_status VARCHAR(32) NOT NULL COMMENT 'New order status',
    old_pay_status VARCHAR(32) DEFAULT NULL COMMENT 'Old pay status',
    new_pay_status VARCHAR(32) DEFAULT NULL COMMENT 'New pay status',
    operate_type VARCHAR(32) NOT NULL COMMENT 'Operate type',
    operate_by BIGINT DEFAULT NULL COMMENT 'Operator id',
    operate_role VARCHAR(32) DEFAULT NULL COMMENT 'Operator role',
    remark VARCHAR(255) DEFAULT NULL COMMENT 'Remark',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
    KEY idx_order_id (order_id),
    KEY idx_order_no (order_no),
    KEY idx_created_at (created_at)
) COMMENT='Order status log';
