server:
  port: 8085

spring:
  application:
    name: pay-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/baimaxt
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  rabbitmq:
    addresses: 192.168.106.101
    username: admin
    password: admin
    virtual-host: /test
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
